pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // libsu publishes through JitPack only.
        maven { url "https://jitpack.io" }
    }
}

rootProject.name = "OpenShrimpCompanion"
include ":app"
