"""One signing key, carried in three files.

The release workflow signs both platforms' appcasts with a single Ed25519
secret, so both front ends have to compile in the same public half: macOS as
``SUPublicEDKey`` in ``Info.plist``, the Windows tray as ``UpdateSigning.PublicKey``
in ``Versions.cs``.  The workflow itself carries a third copy, as the
``SPARKLE_PUBLIC_KEY`` literal the Windows appcast generator verifies its own
output against.

A rotation that reaches one copy and not the others is silent where it matters
most.  A front end left behind fetches the feed, rejects every signature on it,
and goes on reporting nothing to install, which is indistinguishable from being
up to date until somebody reads a log.  A workflow left behind is caught: its
``--verify`` step refuses a feed signed by a key that is not the literal it
holds, so the release fails instead of publishing.
"""

from __future__ import annotations

import base64
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

INFO_PLIST = REPO / "macos" / "App" / "Info.plist"
VERSIONS_CS = REPO / "windows" / "src" / "OpenShrimp.Tray" / "Core" / "Versions.cs"
RELEASE_YAML = REPO / ".github" / "workflows" / "release.yaml"


def _macos_key() -> str:
    """The string element following ``<key>SUPublicEDKey</key>``."""
    text = INFO_PLIST.read_text(encoding="utf-8")
    match = re.search(
        r"<key>SUPublicEDKey</key>\s*<string>([^<]+)</string>", text
    )
    assert match, f"No SUPublicEDKey in {INFO_PLIST}"
    return match.group(1).strip()


def _windows_key() -> str:
    text = VERSIONS_CS.read_text(encoding="utf-8")
    match = re.search(
        r'public\s+const\s+string\s+PublicKey\s*=\s*"([^"]+)"', text
    )
    assert match, f"No UpdateSigning.PublicKey in {VERSIONS_CS}"
    return match.group(1)


def _workflow_keys() -> list[str]:
    """Every ``SPARKLE_PUBLIC_KEY`` literal in the release workflow.

    A list rather than one value: a second appcast generated by a later job
    would carry its own copy, and a rotation has to reach that one too.
    """
    text = RELEASE_YAML.read_text(encoding="utf-8")
    return [m.strip() for m in re.findall(r"SPARKLE_PUBLIC_KEY:\s*(\S+)", text)]


def test_both_platforms_carry_the_same_key() -> None:
    assert _windows_key() == _macos_key()


def test_the_workflow_signs_with_the_key_the_front_ends_verify_against() -> None:
    keys = _workflow_keys()
    assert keys, f"No SPARKLE_PUBLIC_KEY literal in {RELEASE_YAML}"
    assert all(key == _macos_key() for key in keys)


def test_the_key_is_a_32_byte_ed25519_public_half() -> None:
    """What both verifiers decode it as.  A truncated paste parses as base64."""
    assert len(base64.b64decode(_macos_key(), validate=True)) == 32
